In [1]:
import pickle

import torch
import numpy as np


def load_pkl(pickle_file: str) -> object:
    """Load pickle data.

    Args:
        pickle_file (str): file path

    Returns:
        object: loaded objected
        
    """

    try:
        with open(pickle_file, "rb") as f:
            pickle_data = pickle.load(f)
    except UnicodeDecodeError:
        with open(pickle_file, "rb") as f:
            pickle_data = pickle.load(f, encoding="latin1")
    except Exception as e:
        print("Unable to load data ", pickle_file, ":", e)
        raise
    return pickle_data

data_file_path = "data_in2016_out12.pkl"
data_file_path2 = "data_in12_out12.pkl"

data = load_pkl(data_file_path)
data2 = load_pkl(data_file_path2)

print(data['processed_data'].shape)
# print(data2)
# print(list(data['train'][2]))
# print(type(data))
# print(len(data))

(52116, 325, 3)


In [2]:
print(data2['processed_data'].shape)

(52116, 325, 3)


In [3]:
data=load_pkl("index_in2016_out12.pkl")
print(len(data['valid']),len(data['test']),len(data['train']))

5209 10419 34461


In [4]:

print(len(data['train']))
print(len(data['test']))
print(len(data['valid']))
print(data2['processed_data'].shape)
print(data2['processed_data'])

34461
10419
5209
(52116, 325, 3)
[[[9.17990812e-01 0.00000000e+00 6.00000000e+00]
  [5.36523400e-01 0.00000000e+00 6.00000000e+00]
  [8.22623959e-01 0.00000000e+00 6.00000000e+00]
  ...
  [6.42486570e-01 0.00000000e+00 6.00000000e+00]
  [8.86201861e-01 0.00000000e+00 6.00000000e+00]
  [5.57716034e-01 0.00000000e+00 6.00000000e+00]]

 [[9.39183446e-01 3.47222222e-03 6.00000000e+00]
  [5.04734450e-01 3.47222222e-03 6.00000000e+00]
  [8.33220276e-01 3.47222222e-03 6.00000000e+00]
  ...
  [6.00101302e-01 3.47222222e-03 6.00000000e+00]
  [8.54412910e-01 3.47222222e-03 6.00000000e+00]
  [4.94138133e-01 3.47222222e-03 6.00000000e+00]]

 [[9.39183446e-01 6.94444444e-03 6.00000000e+00]
  [5.15330766e-01 6.94444444e-03 6.00000000e+00]
  [7.90835008e-01 6.94444444e-03 6.00000000e+00]
  ...
  [6.00101302e-01 6.94444444e-03 6.00000000e+00]
  [8.22623959e-01 6.94444444e-03 6.00000000e+00]
  [5.47119717e-01 6.94444444e-03 6.00000000e+00]]

 ...

 [[9.17990812e-01 9.89583333e-01 4.00000000e+00]
  [4.4

In [ ]:
tmpl=144
outl=12

In [ ]:
file_name = f'data_in{tmpl}_out{outl}.pkl'
data = {'processed_data':features}
with open(file_name, 'wb') as file:
    pickle.dump(data, file)