In [2]:
import sys
sys.path.append('/home/wbyan/stock_data')
import numpy as np
import pickle
from data_utils import load_data #会显示报错，但是上面加了sys path可以使用
#读取股市数据

date_list, features, labels, stock_list = load_data(
        data_type="ch_daily_processed",
        stock_list="csi500",
        start_date="2010-01-01",
        end_date="2025-01-01",
        contain_bj=False,
        drop_short=False,
        short_len=0,
)


ch_daily_processed csi500
Using the constituent stocks of market index CSI500.
stock list len is  500


100%|██████████| 500/500 [00:00<00:00, 858.07it/s]


Load stock 603049.SH failed.
Load stock 001221.SZ failed.
Use 498 stock, del 2 stock


100%|██████████| 498/498 [00:00<00:00, 2269.54it/s]

feature tensor shape:torch.Size([498, 3608, 45]), label tensor shape:torch.Size([498, 3608, 4]).


In [3]:
features = features.permute(1,0,2)
labels = labels.permute(1,0,2)

In [4]:
print(features.shape)
random = 1000
for i in range(12):
    print(features[i+random][1][:6])
print(f"ans is {features[10+random][1][4]/features[random][1][4] - 1}")
print(f"ans is {features[9+random][1][4]/features[random-1][1][4] - 1}")

torch.Size([3608, 498, 45])
tensor([-0.0017, -0.0392,  0.0555, -0.0420, -0.0319,  0.0076],
       dtype=torch.float64)
tensor([-0.0172, -0.0101,  0.0175, -0.0526,  0.0004,  0.0105],
       dtype=torch.float64)
tensor([ 0.0019, -0.0709,  0.0168, -0.1000, -0.0709,  0.0000],
       dtype=torch.float64)
tensor([-0.0858, -0.0055,  0.0171, -0.0297,  0.0111,  0.0167],
       dtype=torch.float64)
tensor([-0.0791,  0.0287,  0.0431, -0.0065,  0.0326,  0.0038],
       dtype=torch.float64)
tensor([-0.0918,  0.0221,  0.0335, -0.0248,  0.0252,  0.0030],
       dtype=torch.float64)
tensor([-0.0281, -0.0433,  0.0000, -0.0478, -0.0433,  0.0000],
       dtype=torch.float64)
tensor([-0.0880, -0.0340,  0.0152, -0.0327, -0.0154,  0.0192],
       dtype=torch.float64)
tensor([-0.0175,  0.0328,  0.0371, -0.0076,  0.0328,  0.0000],
       dtype=torch.float64)
tensor([-0.0093, -0.0299,  0.0038, -0.0231, -0.0135,  0.0169],
       dtype=torch.float64)
tensor([-0.0503, -0.0019,  0.0288, -0.0216, -0.0023, -0.0004],

In [5]:
# sys.path.append('/home/benyan2023/workspace/STEP/STEP/basicts')
# from utils import load_pkl
# data = load_pkl('data_in144_out12.pkl')
print(features.shape)
random = 1000
ans = 1
# daily_return  = 0
# sum = 0
for i in range(10):
    ans = ans * (1 + features[i+random][1][1])
    # daily_return = (features[i+random+1][1][4] - features[i+random][1][4]) / features[i+random][1][4] * 100
    # sum = sum + daily_return
    print(features[i+random][1][:5])
    # print(f"daily_return : {daily_return}")
# sum = sum / 10
print(f"ans is {ans}")
print(labels[random][1])

torch.Size([3401, 500, 45])
tensor([-0.0007, -0.0778,  0.0157, -0.0909, -0.0841], dtype=torch.float64)
tensor([-0.1203,  0.0306,  0.0436, -0.0361,  0.0376], dtype=torch.float64)
tensor([-0.1040, -0.0217,  0.0261, -0.0428, -0.0203], dtype=torch.float64)
tensor([-0.0854,  0.0311,  0.0400, -0.0222,  0.0319], dtype=torch.float64)
tensor([-0.0492, -0.0172,  0.0043, -0.0287, -0.0165], dtype=torch.float64)
tensor([-0.0772, -0.0219,  0.0074, -0.0141, -0.0081], dtype=torch.float64)
tensor([ 0.0053, -0.0007,  0.0135, -0.0075,  0.0000], dtype=torch.float64)
tensor([-0.0297,  0.0112,  0.0202, -0.0127,  0.0112], dtype=torch.float64)
tensor([ 0.0126,  0.0185,  0.0176, -0.0161,  0.0080], dtype=torch.float64)
tensor([-0.0101, -0.0312,  0.0000, -0.0370, -0.0312], dtype=torch.float64)
ans is 0.9187887130075706
tensor([-0.0023,  0.0053,  1.0000, -0.0778], dtype=torch.float64)


In [6]:

in_length=96
out_length=5
length = features.shape[0]-in_length-out_length
trainl = int(length*0.7)
testl = int(length*0.15)
validl = int(length-trainl-testl)
print(trainl,testl,validl)

idx = {}
train = []
for i in range(trainl):
    train.append((i,i+in_length,i+in_length+out_length))
idx['train']=train
valid=[]
for i in range(trainl,trainl+validl):
    valid.append((i,i+in_length,i+in_length+out_length))
idx['valid']=valid
test=[]
for i in range(trainl+validl,trainl+testl+validl):
    test.append((i,i+in_length,i+in_length+out_length))
idx['test'] =test

file_name = f'index_in{in_length}_out{out_length}.pkl'

with open(file_name,'wb') as file:
    pickle.dump(idx,file)

print(idx['test'],trainl+testl)

2454 526 527
[(2981, 3077, 3082), (2982, 3078, 3083), (2983, 3079, 3084), (2984, 3080, 3085), (2985, 3081, 3086), (2986, 3082, 3087), (2987, 3083, 3088), (2988, 3084, 3089), (2989, 3085, 3090), (2990, 3086, 3091), (2991, 3087, 3092), (2992, 3088, 3093), (2993, 3089, 3094), (2994, 3090, 3095), (2995, 3091, 3096), (2996, 3092, 3097), (2997, 3093, 3098), (2998, 3094, 3099), (2999, 3095, 3100), (3000, 3096, 3101), (3001, 3097, 3102), (3002, 3098, 3103), (3003, 3099, 3104), (3004, 3100, 3105), (3005, 3101, 3106), (3006, 3102, 3107), (3007, 3103, 3108), (3008, 3104, 3109), (3009, 3105, 3110), (3010, 3106, 3111), (3011, 3107, 3112), (3012, 3108, 3113), (3013, 3109, 3114), (3014, 3110, 3115), (3015, 3111, 3116), (3016, 3112, 3117), (3017, 3113, 3118), (3018, 3114, 3119), (3019, 3115, 3120), (3020, 3116, 3121), (3021, 3117, 3122), (3022, 3118, 3123), (3023, 3119, 3124), (3024, 3120, 3125), (3025, 3121, 3126), (3026, 3122, 3127), (3027, 3123, 3128), (3028, 3124, 3129), (3029, 3125, 3130), (3030,

In [7]:
file_name = f'data_in{in_length}_out{out_length}.pkl'
data = {'processed_data':features}
with open(file_name, 'wb') as file:
    pickle.dump(data, file)
print(data['processed_data'][0][0])

tensor([-0.2500,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.2500,  0.2500,
         0.2500,  0.2500,  0.2500,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
         0.0000,  0.0000,  0.1000,  0.1000,  0.9364], dtype=torch.float64)


In [8]:
labels = labels.permute(1,0,2)
print(labels.shape)
file_name = f'label_in{in_length}_out{out_length}.pkl'
data = {'processed_data':labels}
with open(file_name, 'wb') as file:
    pickle.dump(data, file)
print(data['processed_data'][0][0])

torch.Size([498, 3608, 4])
tensor([0., 0., 1., 0.], dtype=torch.float64)


In [9]:
scaler = {}
scaler['func']='re_standard_transform'
scaler['args']={'mean': 0, 'std': 1}

file_name = f'scaler_in{in_length}_out{out_length}.pkl'

with open(file_name,'wb') as file:
    pickle.dump(scaler,file)

In [ ]:
sys.path.append('/home/benyan2023/workspace/STEP/STEP/basicts/utils')

from utils import load_pkl

tmp = load_pkl('scaler_in100_out10.pkl')
print(tmp)